


const ALERT = 'ALERT';
const REFETCH_CHATS = "REFETCH_CHAT";

const NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT";
const NEW_MESSAGE = "NEW_MESSAGE";

const NEW_REQUEST = "NEW MESSAGE_ALERT";

const START_TYPING = "START_TYPING";
const STOP_TYPING = "STOP_TYPING";

const CHAT_JOINED = "CHAT_JOINED";
const CHAT_LEAVED = "CHAT_LEAVED";
const ONLINE_USERS = "ONLINE_USERS"

export {ALERT,REFETCH_CHATS,NEW_MESSAGE,NEW_MESSAGE_ALERT,NEW_REQUEST,START_TYPING,STOP_TYPING,CHAT_JOINED,CHAT_LEAVED,ONLINE_USERS};