


const ALERT = 'ALERT';
const REFETCH_CHATS = "REFETCH_CHAT";

const NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT";
const NEW_MESSAGE = "NEW_MESSAGE";

const NEW_REQUEST = "NEW MESSAGE_ALERT";


export {ALERT,REFETCH_CHATS,NEW_MESSAGE,NEW_MESSAGE_ALERT,NEW_REQUEST};